### ISSUE TITLE
Allow a column to separate chains in mcmc plots

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/bayesplot#12]
It could make sense too add another argument naming a column in the data.frame / matrix (defaulting to `NULL` or so) that -- if present -- would allow separating chains. This way one would not be forced to use 3D arrays.

**Comment by jgabry** [comment]
Do you mean so you could use a data.frame that has the chains stacked and
not necessarily in order?

**Comment by paul-buerkner** [comment]
Excatly :-)

**Comment by jgabry** [comment]
Ok will do

**Comment by jgabry** [comment]
right now this just converts the `data.frame` to a 3D `array` and proceeds as before. but maybe it would be better to always use tall data internally
