### ISSUE TITLE
Change global theme of plots?

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/bayesplot#15]
This is more like a questions: Is is possible to change the overall theme of the plots product by bayesplot?

**Comment by jgabry** [comment]
I'm not sure actually. I'm not looking at it right now but if it doesn't
work to just do something like `plot + theme_whatever()` then I should
figure out how to add the default bayesplot theme without preventing people
from changing it.

**Comment by paul-buerkner** [comment]
`plot + theme_whatever()` appears to work in most cases, but I had some problems with it yesterday. Let's see if I can reproduce it.

**Comment by jgabry** [comment]
One thing is that it's probably not going to work with mcmc_combo since
that returns the result of arrangeGrob rather than a ggplot object.

**Comment by paul-buerkner** [comment]
Yep, that's one reason I currently don't use mcmc_combo in brms and instead
combine mcmc_trace and mcmcm_dens_overlay plots manually.

2016-06-20 15:58 GMT+02:00 Jonah Gabry <notifications@github.com>:

**Comment by jgabry** [comment]
@paul-buerkner does the `gg_theme` argument I just added to `mcmc_combo` let you change what you want to change for brms? you should now be able to do something like 

```r
mcmc_combo(x, gg_theme = theme_gray())
```

**Comment by paul-buerkner** [comment]
Not exactly, because I want to amend the ggplot objects separately (see https://github.com/paul-buerkner/brms/blob/use_bayesplot_package/R/brmsfit-methods.R  line 819 ff.) I don't mind not calling mcmc_combo in this case so you don't have to adjust for this situation. After all, mcmc_combo is thought of a convenience functions I think that doesn't need to allow every kind of tweaking.

**Comment by jgabry** [comment]
Ok, I see. 

Looking at your code did remind me though that it might be a good idea for bayesplot plot to make it easy to split plots over multiple pages. Or do you think that should be left up to the user or developer using the package?

**Comment by paul-buerkner** [comment]
Hmm that's a good question. It wouldn't do harm to implement this option in bayesplot I guess, if it's not too complicated. It may not necessarily be high priority though.

**Comment by jgabry** [comment]
@paul-buerkner I think changing the global theme of plots by adding ggplot theme objects should be working fine. If it's not a problem anymore for you I'll close this issue.

**Comment by paul-buerkner** [comment]
Thanks, that works!
