### ISSUE TITLE
Problems when calling mcmc plots with only one parameter

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/bayesplot#16]
Minimal example: 
```R
mcmc_trace(data.frame(b = rnorm(100)))
```

Another error occurs when adding a chain column:
```R
mcmc_trace(data.frame(b = rnorm(100), chain = 1))
```

**Comment by jgabry** [comment]
Thanks. I still need to add tests for all the various input types (df vs
matrix vs array) and edge cases (eg 1 chain, 1 parameter). There are tests
for the ppc plots but essentially zero for the mcmc plots
