### ISSUE TITLE
Allow to plot residuals in ppc_scatter*

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/bayesplot#18]
Right now, the x-axis of the pp_scatter* plots are displaying y, but it users may also want to see the residuals (y - yrep) since this resembles the standard residual plots generated for instance by `plot(<lm object>)` (except that y is plotted on the y-axis there). Do you think it makes sense adding an option to show residuals instead of y itself?

**Comment by jgabry** [comment]
How about replacing `ppc_resid` with two functions `ppc_resid_hist` and `ppc_resid_scatter`, the first of which is the same as `ppc_resid` now and the second that creates the plot you're describing? Or do you think it would be better to put this plot with the rest of the scatterplots as opposed to the residual plots?

**Comment by paul-buerkner** [comment]
I think your idea of replacing `ppc_resid` makes most sense as it is more intuitive for users.
