### ISSUE TITLE
Is GGally worth it? 

### ISSUE THREAD

**Issue by jgabry** [jgabry/bayesplot#23]
Is **GGally**'s pair plot useful enough to warrant using it for `mcmc_pairs` and keeping **GGally** in `Suggests`? Currently this is what `mcmc_pairs` uses, but it might be more trouble than it's worth. Working with `ggpairs` is pretty cumbersome, and although the plot looks ok, it isn't flexible enough to be easily extended to include functionality similar to `rstan::pairs.stanfit`, which is what really makes pairs plots very useful.

**Comment by paul-buerkner** [comment]
I didn't take a look at the code of `rstan::pairs.stanfit`, but as far as I understand the purpose of the `bayesplot` package it should be used as a backend for all plots in `rstan` too. I think you might hesitate in the end replacing the existing `rstan::pairs.stanfit` methods with something that is less flexible.

**Comment by jgabry** [comment]
Yeah I agree, I'm thinking I'll just drop the pairs plot for now until I
have time (or someone else does) to do a real ggplot substitute for
pairs.stanfit.
