### ISSUE TITLE
Check that plots look ok with all colors schemes

### ISSUE THREAD

**Issue by jgabry** [jgabry/bayesplot#25]

**Comment by paul-buerkner** [comment]
Attached is a .zip file showing all ppc plots with all color schemes:  [ppc_plots.zip](https://github.com/jgabry/bayesplot/files/429848/ppc_plots.zip)

Most of them look pretty good and consistent. I have some comments though:

1. The mixed color schemes have somewhat suboptimal contrasts. For instance, in the red-blue scheme, dark red edges are hard to discriminate from the main dark blue surface. 

2. The color of the dot edges and the color of the dot surfaces interchanges between plots in all mixed schemes. For instance, while `ppc_scatter` has blue egdes and red surfaces, it is the other way round in `ppc_stat_2d`.

2. The brightest yellow colors are hard to discriminate from the white background depending on the contrast of the monitor.

**Comment by jgabry** [comment]
Thanks that's super helpful. I'll make some tweaks.

**Comment by jgabry** [comment]
For the yellow scheme it's true that the white background isn't ideal. But I've added a `plot_bg` helper function that lets you easily change the plot background. So if someone wants to use the yellow scheme they can use a dark background, for example: 

The default with the yellow scheme would look like this

```r
set_color_scheme("yellow")
ppc_dens_overlay(y, yrep[1:40, ])
```
![a](https://cloud.githubusercontent.com/assets/7796803/18036565/af1920cc-6d3b-11e6-8351-24ac7fbc5e38.png)

and simply adding `+ plot_bg(fill = "gray20")` would give you this

```r
set_color_scheme("yellow")
ppc_dens_overlay(y, yrep[1:40, ]) + plot_bg(fill = "gray20")
```
![b](https://cloud.githubusercontent.com/assets/7796803/18036566/b483ea56-6d3b-11e6-97c3-85a46cc2a583.png)


Thoughts?

**Comment by paul-buerkner** [comment]
This looks great!

**Comment by jgabry** [comment]
* [ ] Check mcmc plots with color schemes like Paul did for ppc plots

**Comment by paul-buerkner** [comment]
Attached are all mcmc plots in all color schemes. I don't really like the red and yellow color schemes. The red one is not really red; the colors could be more intense. Same with yellow although I see that this improves when chaning the background. Also, did you think of adding an orange color scheme?
[mcmc_plots.zip](https://github.com/jgabry/bayesplot/files/450489/mcmc_plots.zip)

**Comment by jgabry** [comment]
Awesome thanks Paul!

As for the color schemes, I actually like the red one! I've always tended
to prefer more muted colors, but I might very well be in the minority
there. I have no problem adding more bright schemes. For starters what
about adding a "brightred" scheme like there is for "blue" and
"brightblue"?

I agree with you about the yellow scheme. It was hard to find a set of
yellows that work, and I don't think I fully succeeded.

There's an example of manually defining an orange scheme in the examples
for set_color_scheme but I didn't really make sure it looks good. I'm ok
with adding an official orange scheme but all the dark oranges I tried
looked pretty ugly. If you have a recommendation for a set of 6 oranges I'd
be happy to add it.

**Comment by paul-buerkner** [comment]
The Idea with the "brightred" sounds good. I guess having no official
orange theme is ok for the initial release . Maybe we find one for one of
the next releases. After all it's not of high priority, since you already
implemented so many good looking color schemes.

2016-09-02 0:06 GMT+02:00 Jonah Gabry <notifications@github.com>:

> Awesome thanks Paul!
>
> As for the color schemes, I actually like the red one! I've always tended
> to prefer more muted colors, but I might very well be in the minority
> there. I have no problem adding more bright schemes. For starters what
> about adding a "brightred" scheme like there is for "blue" and
> "brightblue"?
>
> I agree with you about the yellow scheme. It was hard to find a set of
> yellows that work, and I don't think I fully succeeded.
>
> There's an example of manually defining an orange scheme in the examples
> for set_color_scheme but I didn't really make sure it looks good. I'm ok
> with adding an official orange scheme but all the dark oranges I tried
> looked pretty ugly. If you have a recommendation for a set of 6 oranges I'd
> be happy to add it.
>
> On Thursday, September 1, 2016, Paul-Christian Bürkner <

**Comment by jgabry** [comment]
Ok sounds good. Now I just need to find the right "brightred" colors. It's
harder than it might seem!

**Comment by jgabry** [comment]
@paul-buerkner Any suggestions for colors to use in the `"brightred"` scheme? I've tried some things but nothing that looks good. If you want to try out some colors it's pretty easy to set a custom color palette with 

```r
set_color_scheme(scheme)
```

if `scheme` is any vector of 6 colors. 

And I just added a `view_color_scheme` function that makes plots like this

```r
set_color_scheme("brightblue")
view_color_scheme()
```
![brightblue](https://cloud.githubusercontent.com/assets/7796803/18233782/4380d890-72be-11e6-8d8e-af3e27230259.png)

and this

```r
view_color_scheme(c("pink", "gray", "teal"))
```
![pinkgrayteal](https://cloud.githubusercontent.com/assets/7796803/18233784/495a6e84-72be-11e6-96cc-754c5d3fb774.png)

**Comment by paul-buerkner** [comment]
You are right, it's not easy to get a nice looking scheme. Here is my proposal, which isn't necessarily ideal yet...

```R
set_color_scheme(c("#ffa1a1", "#ff7373", "#ff4646", 
                   "#ff0000", "red3", "red4"))
```

I am totally fine with not adding a "brightred" scheme for now if you don't like it and we cannot find a better looking one.

[brightred_scheme.pdf](https://github.com/jgabry/bayesplot/files/455209/brightred_scheme.pdf)
[ppc_plots_red.pdf](https://github.com/jgabry/bayesplot/files/455210/ppc_plots_red.pdf)

**Comment by jgabry** [comment]
Hmm yeah, that's similar to what I had. It's the lighter colors that are hard to get right I think. Maybe a color scheme that's a mix of reds and grays or something like that?

**Comment by paul-buerkner** [comment]
Possibly. I am not an expert in color schemes though and I am fine with not including a "brightred" color scheme in the first release. Maybe you or I come up with a good solution later on.

**Comment by jgabry** [comment]
Ok same here. Maybe if people end up using the custom color scheme feature
then eventually we can incorporate some of what people come up with. I'm
definitely far from an expert in color palettes.
>
>
