### ISSUE TITLE
ppc_vs_x_grouped cannot handle argument 'time'

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/bayesplot#26]
When you accidently pass the `time` argument to `ppc_vs_x_grouped` it is further passed to `ppc_ts_grouped`, although `x` is already used as the `time` argument here. This leads to duplicated assignments of the latter argument causing an error. Is it possible to just ignore the `time` argument in `ppc_vs_x_grouped` instead of passing it further?

**Comment by jgabry** [comment]
Ok thanks, I hadn't noticed that, I'll sort it out.
